In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.preprocessing import StandardScaler

In [2]:
data=pd.read_csv('pollution.csv')

In [3]:
data.head()

AirPollutionIndex  CO2Emissions  IndustrialWaste  EnergyRecovered
0          37.454012     92.566464        52.341137        42.605549
1          95.071431    270.950474        49.395760       102.956294
2          73.199394    436.472918       181.250916       112.604882
3          59.865848    366.112443        49.909240        84.504932
4          15.601864    403.280574        54.389945        95.137492

In [5]:
data.corr()['EnergyRecovered']

AirPollutionIndex    0.436572
CO2Emissions         0.848189
IndustrialWaste     -0.132065
EnergyRecovered      1.000000
Name: EnergyRecovered, dtype: float64

In [8]:
x=data[['AirPollutionIndex','CO2Emissions','IndustrialWaste']].values

In [9]:
x

array([[ 37.45401188,  92.56646442,  52.34113675],
       [ 95.07143064, 270.95047369,  49.39575981],
       [ 73.19939418, 436.47291794, 181.2509161 ],
       ...,
       [ 13.68186309,  34.47900818,  61.95757184],
       [ 95.02373538,  28.52736058,  58.00910639],
       [ 44.6005773 , 141.09353735, 174.28280684]])

In [10]:
y=data['EnergyRecovered'].values

In [11]:
y.shape

(1000,)

In [14]:
y

array([[ 4.26055490e+01],
       [ 1.02956294e+02],
       [ 1.12604882e+02],
       [ 8.45049317e+01],
       [ 9.51374921e+01],
       [ 6.11026028e+01],
       [ 5.94442688e+01],
       [ 1.14128046e+02],
       [ 3.59528760e+01],
       [ 7.86812295e+01],
       [ 1.21841818e+01],
       [ 1.32482526e+02],
       [ 1.02675725e+02],
       [ 2.29016130e+01],
       [ 6.27077180e+01],
       [ 1.08810422e+02],
       [ 2.09647655e+01],
       [ 4.79620981e+01],
       [ 1.01544368e+02],
       [ 1.70383773e+01],
       [ 7.95078010e+01],
       [ 2.00233571e+01],
       [ 8.99105850e+01],
       [ 1.19396586e+02],
       [ 1.20028270e+02],
       [ 9.59620562e+01],
       [ 7.79738484e+01],
       [ 7.72802431e+01],
       [ 5.22655229e+01],
       [ 7.47333811e+01],
       [ 2.04784641e+01],
       [ 4.72750798e+01],
       [ 2.04126925e+01],
       [ 3.95743353e+01],
       [ 4.41343463e+01],
       [ 9.54736642e+01],
       [ 4.46322620e+01],
       [ 6.50930148e+01],
       [ 4.5

In [12]:
if y.ndim == 1:
    y = y.reshape(-1, 1)

In [13]:
y.shape

(1000, 1)

In [15]:
y

array([[ 4.26055490e+01],
       [ 1.02956294e+02],
       [ 1.12604882e+02],
       [ 8.45049317e+01],
       [ 9.51374921e+01],
       [ 6.11026028e+01],
       [ 5.94442688e+01],
       [ 1.14128046e+02],
       [ 3.59528760e+01],
       [ 7.86812295e+01],
       [ 1.21841818e+01],
       [ 1.32482526e+02],
       [ 1.02675725e+02],
       [ 2.29016130e+01],
       [ 6.27077180e+01],
       [ 1.08810422e+02],
       [ 2.09647655e+01],
       [ 4.79620981e+01],
       [ 1.01544368e+02],
       [ 1.70383773e+01],
       [ 7.95078010e+01],
       [ 2.00233571e+01],
       [ 8.99105850e+01],
       [ 1.19396586e+02],
       [ 1.20028270e+02],
       [ 9.59620562e+01],
       [ 7.79738484e+01],
       [ 7.72802431e+01],
       [ 5.22655229e+01],
       [ 7.47333811e+01],
       [ 2.04784641e+01],
       [ 4.72750798e+01],
       [ 2.04126925e+01],
       [ 3.95743353e+01],
       [ 4.41343463e+01],
       [ 9.54736642e+01],
       [ 4.46322620e+01],
       [ 6.50930148e+01],
       [ 4.5

In [23]:
x.shape

(1000, 3)

In [16]:
scaler=StandardScaler()
x_scaled=scaler.fit_transform(x)
y_scaled=scaler.fit_transform(y)


In [22]:
x_scaled.shape

(1000, 3)

In [18]:
y_scaled

array([[-6.56874612e-01],
       [ 1.09849588e+00],
       [ 1.37913612e+00],
       [ 5.61816896e-01],
       [ 8.71077086e-01],
       [-1.18866631e-01],
       [-1.67101171e-01],
       [ 1.42343908e+00],
       [-8.50375222e-01],
       [ 3.92427850e-01],
       [-1.54171490e+00],
       [ 1.95730016e+00],
       [ 1.09033522e+00],
       [-1.22998615e+00],
       [-7.21800156e-02],
       [ 1.26876991e+00],
       [-1.28632157e+00],
       [-5.01073249e-01],
       [ 1.05742841e+00],
       [-1.40052507e+00],
       [ 4.16469628e-01],
       [-1.31370351e+00],
       [ 7.19046508e-01],
       [ 1.57668061e+00],
       [ 1.59505385e+00],
       [ 8.95060476e-01],
       [ 3.71852862e-01],
       [ 3.51678557e-01],
       [-3.75903214e-01],
       [ 2.77600160e-01],
       [-1.30046620e+00],
       [-5.21055964e-01],
       [-1.30237925e+00],
       [-7.45040931e-01],
       [-6.12407792e-01],
       [ 8.80855035e-01],
       [-5.97925345e-01],
       [-2.80092756e-03],
       [-5.8

In [19]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [21]:
x_train.shape

(800, 3)

In [20]:
model=Sequential([
    Dense(64,activation='relu',input_shape=(x_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1,activation='linear')
])

C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [24]:
model.compile(optimizer=Adam(learning_rate=0.001),loss='mse')

In [25]:
history=model.fit(x_train,y_train,epochs=100,validation_split=0.2,verbose=1)

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 1941.0540 - val_loss: 501.8257
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 447.3714 - val_loss: 308.5580
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 232.9600 - val_loss: 219.4099
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 176.3822 - val_loss: 133.0326
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 114.1870 - val_loss: 106.3705
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 92.2494 - val_loss: 106.5901
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.7302 - val_loss: 108.9829
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 101.7134 - val_loss: 108.4489
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 104.5626 - val_loss: 109.3155
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 103.6896 - val_loss: 110.2508
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 93.6767 - val_loss: 116.2589
Epoch 12/100
20/20 ━━

In [27]:
history

In [26]:
y_pred=model.predict(x_test)

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step 


In [28]:
y_pred

array([[106.14087  ],
       [ 50.142353 ],
       [ 97.44395  ],
       [ 68.03813  ],
       [ 50.94044  ],
       [ 58.529324 ],
       [ 41.109264 ],
       [ 43.895325 ],
       [ 70.58006  ],
       [105.82068  ],
       [105.06088  ],
       [ 71.58487  ],
       [ 46.398045 ],
       [ 48.983032 ],
       [ 40.92768  ],
       [ 90.05675  ],
       [ 99.80502  ],
       [ 82.14801  ],
       [ 97.143906 ],
       [ 10.302891 ],
       [ 96.69604  ],
       [ 90.04482  ],
       [  8.332454 ],
       [ 25.054035 ],
       [ 55.31996  ],
       [ 61.054214 ],
       [116.81484  ],
       [102.06328  ],
       [ 90.19331  ],
       [ 51.082966 ],
       [ 52.140312 ],
       [ 89.43268  ],
       [  4.8459144],
       [126.39662  ],
       [ 87.925674 ],
       [107.79422  ],
       [ 54.26844  ],
       [117.50049  ],
       [-16.567858 ],
       [ 67.742165 ],
       [ 73.80771  ],
       [ 34.452522 ],
       [ 45.235924 ],
       [ 24.858261 ],
       [ 67.244286 ],
       [11

In [29]:
y_test

array([[ 1.14383310e+02],
       [ 6.15922844e+01],
       [ 8.03943716e+01],
       [ 6.74822717e+01],
       [ 4.78408433e+01],
       [ 5.84976620e+01],
       [ 5.40713810e+01],
       [ 4.17313981e+01],
       [ 7.71423174e+01],
       [ 1.05600784e+02],
       [ 1.10128909e+02],
       [ 7.79408322e+01],
       [ 4.60144155e+01],
       [ 5.04457767e+01],
       [ 3.03913476e+01],
       [ 6.33241687e+01],
       [ 1.04193764e+02],
       [ 9.90086080e+01],
       [ 9.70335909e+01],
       [ 1.65832411e+01],
       [ 1.03484149e+02],
       [ 1.00333634e+02],
       [-2.96076775e+00],
       [ 1.85725941e+01],
       [ 4.48366221e+01],
       [ 5.48540359e+01],
       [ 1.09751984e+02],
       [ 9.25224345e+01],
       [ 9.15572167e+01],
       [ 4.01133049e+01],
       [ 6.35924499e+01],
       [ 7.14696100e+01],
       [-2.04208293e+00],
       [ 1.22100991e+02],
       [ 1.08674151e+02],
       [ 1.18600373e+02],
       [ 5.61369308e+01],
       [ 1.27491767e+02],
       [-1.0

In [30]:
mse=mean_squared_error(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)
print("Mean Squared Error:",mse)
print("Mean Absolute Error:",mae)
print("R2 Score:",r2)

Mean Squared Error: 114.80019378533278
Mean Absolute Error: 8.97742807016671
R2 Score: 0.9069783920375561
