In [61]:
print("Hello World")

Hello World


In [62]:
import numpy as np
import pandas as pd

In [63]:
data=pd.read_csv("deforestation_dataset.csv")

In [64]:
data.head()

Country  Year  Forest_Loss_Area_km2  Tree_Cover_Loss_percent  \
0  Indonesia  1971                   560                 8.929641   
1     Brazil  1927                  3303                 4.638441   
2     Russia  1961                  4466                 4.679313   
3  Australia  1967                  3658                 1.535528   
4  Australia  1987                  2682                 8.035841   

   CO2_Emission_mt  Rainfall_mm  Population  GDP_Billion_USD  \
0              304  1635.715350    86759840      2551.805035   
1              341  1454.430241    83798502      2637.895996   
2              298  1744.809660    41477592      2880.724721   
3              285  1541.645853    71475964      2525.516988   
4              450  1752.997736    16256333       608.916586   

   Agriculture_Land_Percent  Deforestation_Policy_Strictness  \
0                 59.316366                                3   
1                 14.211099                                4   
2                 44.869699                                2   
3                 10.824516                                4   
4                 14.577190                                4   

   Corruption_Index  International_Aid_Million_USD  \
0          9.426264                            238   
1          2.602618                            418   
2         51.917315                            186   
3         23.716328                            190   
4         21.424037                            159   

   Illegal_Lumbering_Incidents  Protected_Areas_Percent  
0                          184                 7.005531  
1                           78                20.044415  
2                           49                22.747603  
3                            2                22.701362  
4                           41                18.085869

In [65]:
data['Deforestation_level']=data['Tree_Cover_Loss_percent']*(data['Forest_Loss_Area_km2']+data['Protected_Areas_Percent'])

In [66]:
data.select_dtypes(include=['float64', 'int64']).corr()['Deforestation_level']

Year                               0.109145
Forest_Loss_Area_km2               0.720688
Tree_Cover_Loss_percent            0.597651
CO2_Emission_mt                   -0.055730
Rainfall_mm                       -0.005383
Population                        -0.206690
GDP_Billion_USD                   -0.064496
Agriculture_Land_Percent           0.002843
Deforestation_Policy_Strictness   -0.066898
Corruption_Index                  -0.103546
International_Aid_Million_USD      0.030205
Illegal_Lumbering_Incidents        0.049761
Protected_Areas_Percent            0.250780
Deforestation_level                1.000000
Name: Deforestation_level, dtype: float64

In [67]:
features=data[['Forest_Loss_Area_km2','Tree_Cover_Loss_percent']]
x=np.array(features)

In [68]:
y=data['Deforestation_level']
y=np.array(y)

In [69]:
x

array([[5.60000000e+02, 8.92964087e+00],
       [3.30300000e+03, 4.63844131e+00],
       [4.46600000e+03, 4.67931297e+00],
       [3.65800000e+03, 1.53552757e+00],
       [2.68200000e+03, 8.03584145e+00],
       [3.59300000e+03, 1.67174185e+00],
       [2.77900000e+03, 9.53183686e+00],
       [6.09000000e+02, 3.03197398e+00],
       [2.32600000e+03, 3.96131047e+00],
       [9.36000000e+02, 4.05804025e+00],
       [2.40700000e+03, 3.05545699e+00],
       [3.86200000e+03, 2.36663822e+00],
       [5.03000000e+02, 5.85153157e+00],
       [1.66000000e+03, 9.79185137e+00],
       [4.10700000e+03, 1.75637560e+00],
       [1.76200000e+03, 9.03261934e+00],
       [2.92000000e+03, 5.49088822e+00],
       [3.15000000e+03, 5.87132609e+00],
       [3.27600000e+03, 9.14701677e+00],
       [1.05200000e+03, 7.77558001e+00],
       [2.01000000e+03, 4.90236824e+00],
       [3.26800000e+03, 7.34602978e+00],
       [1.28700000e+03, 2.90261287e+00],
       [4.68300000e+03, 6.66716742e+00],
       [3.648000

In [70]:
y.reshape(-1,1)

array([[ 5063.15576639],
       [15413.74649563],
       [21004.25488126],
       [ 5651.8184299 ],
       [21697.46193265],
       [ 6037.4678898 ],
       [26711.48310717],
       [ 1930.32086885],
       [ 9313.71217216],
       [ 3906.91166071],
       [ 7398.6947142 ],
       [ 9184.21685172],
       [ 3002.58089745],
       [16315.83762029],
       [ 7257.94010179],
       [16101.86729876],
       [16114.60654734],
       [18598.50040533],
       [30188.32304685],
       [ 8367.26622329],
       [ 9963.95535123],
       [24208.35287561],
       [ 3774.83069579],
       [31404.95205206],
       [15536.74876338],
       [42629.74722231],
       [11291.71353503],
       [ 8220.75720865],
       [22822.87350228],
       [ 1629.6299224 ],
       [ 7206.86668039],
       [ 2858.37491552],
       [12098.00525148],
       [ 5187.27025606],
       [18590.40756942],
       [ 7492.45405979],
       [18394.62225141],
       [13521.6710082 ],
       [43637.80257617],
       [23411.48582247],


In [71]:
from sklearn import svm
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_scaled=scaler.fit_transform(x)
y_scaled=scaler.fit_transform(y.reshape(-1,1))

In [72]:
x_scaled

array([[-1.43584658,  1.35335382],
       [ 0.70228678, -0.38110319],
       [ 1.60883037, -0.3645833 ],
       [ 0.97900473, -1.63526776],
       [ 0.21822523,  0.99208965],
       [ 0.92833806, -1.58021141],
       [ 0.29383549,  1.59675501],
       [-1.3976517 , -1.03042011],
       [-0.05927221, -0.65479224],
       [-1.14275939, -0.61569509],
       [ 0.00386626, -1.02092853],
       [ 1.13802011, -1.29934172],
       [-1.48027735,  0.10921493],
       [-0.57841067,  1.70185009],
       [ 1.32899447, -1.54600335],
       [-0.49890298,  1.39497662],
       [ 0.40374318, -0.03655325],
       [ 0.58302524,  0.11721567],
       [ 0.68124062,  1.44121484],
       [-1.05233888,  0.88689475],
       [-0.30559016, -0.27442674],
       [ 0.67500472,  0.71327514],
       [-0.86915939, -1.08270649],
       [ 1.77797909,  0.43888623],
       [ 0.97120985, -0.53807235],
       [ 1.90191755,  1.28213422],
       [ 0.79972267, -0.93024037],
       [-0.18788759, -0.72237919],
       [ 1.66339448,

In [73]:
y_scaled

array([[-0.83514883],
       [ 0.19358466],
       [ 0.74921896],
       [-0.77664232],
       [ 0.81811602],
       [-0.73831305],
       [ 1.31645391],
       [-1.14651774],
       [-0.41269084],
       [-0.95006662],
       [-0.60302226],
       [-0.42556124],
       [-1.03994703],
       [ 0.28324248],
       [-0.6170117 ],
       [ 0.26197621],
       [ 0.26324235],
       [ 0.51011375],
       [ 1.6620131 ],
       [-0.50675703],
       [-0.34806391],
       [ 1.06767063],
       [-0.963194  ],
       [ 1.78293248],
       [ 0.20580972],
       [ 2.89855216],
       [-0.21609953],
       [-0.5213184 ],
       [ 0.92996941],
       [-1.17640308],
       [-0.62208783],
       [-1.0542795 ],
       [-0.13596311],
       [-0.82281323],
       [ 0.50930941],
       [-0.59370362],
       [ 0.48985053],
       [ 0.00553342],
       [ 2.99874164],
       [ 0.98847092],
       [-1.04861689],
       [-0.2993221 ],
       [-1.05239093],
       [-1.1654677 ],
       [-0.36818692],
       [-0

In [74]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [77]:
from sklearn.svm import SVR

svr_linear=SVR(kernel='linear',C=1.0,epsilon=0.1)
svr_linear.fit(x_train, y_train)

SVR(kernel='linear')

In [79]:
y_pred_scaled = svr_linear.predict(x_test)


In [80]:
y_pred=scaler.inverse_transform(y_pred_scaled.reshape(-1,1)).flatten()

In [82]:
y_pred

array([2.06604849e+08, 6.37357417e+07, 1.37982372e+08, 1.05144257e+08,
       7.32833627e+07, 1.73802392e+08, 6.46372690e+07, 3.37844144e+07,
       1.20491700e+08, 3.91513787e+07, 1.74328930e+08, 5.33585420e+07,
       3.30415862e+07, 4.50917584e+07, 1.35508046e+08, 1.42895247e+08,
       1.36400771e+08, 9.14401877e+07, 3.09113016e+07, 7.55543885e+07])

In [83]:
y_test

array([34437.18804994,  4406.78965817, 15390.07788582, 13106.16348641,
        9761.4878555 , 23411.48582247,  3774.83069579,  3281.14335471,
        7398.6947142 ,  5063.15576639, 30188.32304685,  7206.86668039,
        1953.4169562 ,  5187.27025606, 17068.48099473, 21697.46193265,
       10298.43560694, 12001.49294634,  3002.58089745,  2858.37491552])

In [85]:

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score


mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("SVR Linear Model Performance:")
print(f"MAE: {mae:.2f}")
print(f"MSE: {mse:.2f}")
print(f"RMSE: {rmse:.2f}")
print(f"R²: {r2:.2f}")

SVR Linear Model Performance:
MAE: 96845850.04
MSE: 12125124684601628.00
RMSE: 110114143.89
R²: -142091520.65
